# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gameover < Formula
  desc "Play text-based games right in your terminal."
  homepage ""
  version "0.0.2"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kbrgl/gameover/releases/download/v0.0.2/gameover_0.0.2_darwin_arm64.tar.gz"
      sha256 "c3a8d109f884af4c27e4b5a4a0be17e106181a3787f74c3c4caa41fdf4e96f96"

      def install
        bin.install "gameover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kbrgl/gameover/releases/download/v0.0.2/gameover_0.0.2_darwin_amd64.tar.gz"
      sha256 "1f9adffc9997ee5fa174f60c33d3029e8f3ee9938ff4fa5d0e7429eed55a1598"

      def install
        bin.install "gameover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kbrgl/gameover/releases/download/v0.0.2/gameover_0.0.2_linux_arm64.tar.gz"
      sha256 "a4cdc7ef73b71f0ee2c4a657185768b996b01405f4994725028b1e980db7453c"

      def install
        bin.install "gameover"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kbrgl/gameover/releases/download/v0.0.2/gameover_0.0.2_linux_amd64.tar.gz"
      sha256 "4a685b0456a2c3f713378a77ca12fa46bdab302b0cf74c3ba0231b8ca5c62840"

      def install
        bin.install "gameover"
      end
    end
  end

  depends_on "go"

  def caveats; <<~EOS
    Gameover is installed. Run `gameover init` to get started!
  EOS
  end
end
